kind: pipeline
name: Build Tests

platform:
  os: linux
  arch: amd64

steps:
- name: Tests
  image: abcminiuser/docker-ci-python:latest
  pull: always
  commands:
  - python src/test.py

- name: Flake8
  image: abcminiuser/docker-ci-python:latest
  pull: always
  commands:
  - flake8 --ignore E501 src/

- name: Bandit
  image: abcminiuser/docker-ci-python:latest
  pull: always
  commands:
  - bandit -r src/

- name: Documentation
  image: abcminiuser/docker-ci-python:latest
  pull: always
  commands:
  - make -C doc html

- name: Packaging
  image: abcminiuser/docker-ci-python:latest
  pull: always
  commands:
  - python setup.py sdist bdist_wheel
  - twine check dist/*
