kind: pipeline
type: docker
name: Build Tests

platform:
  os: linux
  arch: amd64

steps:
- name: "Ruff Check"
  image: abcminiuser/docker-ci-python:latest
  pull: always
  commands:
  - pip install ruff
  - ruff check

- name: "Ruff Format"
  image: abcminiuser/docker-ci-python:latest
  pull: always
  commands:
  - pip install ruff
  - ruff format --exit-non-zero-on-format

- name: Pyright
  image: abcminiuser/docker-ci-python:latest
  pull: always
  commands:
  - pip install pyright
  - pip install -r requirements.txt
  - pyright

- name: Tests
  image: abcminiuser/docker-ci-python:latest
  pull: always
  commands:
  - apk add jpeg-dev zlib-dev
  - pip install Pillow
  - python test/test.py

- name: Documentation
  image: abcminiuser/docker-ci-python:latest
  pull: always
  commands:
  - make -C doc html

- name: Packaging
  image: abcminiuser/docker-ci-python:latest
  pull: always
  commands:
  - python -m build
  - twine check dist/*
  depends_on:
  - "Ruff Check"
  - "Ruff Format"
  - Pyright
  - Tests
  - Documentation
