kind: pipeline
type: docker
name: Build Tests

platform:
  os: linux
  arch: amd64

steps:
- name: Flake8
  image: abcminiuser/docker-ci-python:latest
  pull: always
  commands:
  - flake8 --config .flake8 src/

- name: Bandit
  image: abcminiuser/docker-ci-python:latest
  pull: always
  commands:
  - bandit --ini .bandit -r src/

- name: MyPy
  image: abcminiuser/docker-ci-python:latest
  pull: always
  commands:
  - mypy --ignore-missing-imports src/

- name: Tests
  image: abcminiuser/docker-ci-python:latest
  pull: always
  commands:
  - apk add jpeg-dev zlib-dev
  - pip install Pillow
  - python test/test.py

- name: Documentation
  image: abcminiuser/docker-ci-python:latest
  pull: always
  commands:
  - make -C doc html

- name: Packaging
  image: abcminiuser/docker-ci-python:latest
  pull: always
  commands:
  - python setup.py sdist bdist_wheel
  - twine check dist/*
  depends_on:
  - Flake8
  - Bandit
  - MyPy
  - Tests
  - Documentation
