target-version = "py310"

line-length = 100
indent-width = 4

exclude = ['doc/']

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true

[lint]
extend-select = ["B"]

unfixable = ["B"]

ignore = [
	'N999', # Too late to adhere to the standard class naming conventions now.
	'C408', # I like my explicit empty dict()/list().
	'SIM102', # Sometimes nested 'if' reads better than a giant multi-conditional.
	'BLE001', # We do bare exception catching in several places, deliberately.
	'EXE001', # Python files aren't marked as executable currently.
]

[lint.isort]
split-on-trailing-comma = false

[lint.per-file-ignores]
"test/*.py" = [
	'F841', # Tests don't use the values of many local variables after a call.
	'B007', # Tests sometimes don't use an unpacked variable for clarity.
]
"src/example_*.py" = [
	'RUF059', # Examples sometimes don't use an unpacked variable for clarity.
	'B007', # Examples sometimes don't use an unpacked variable for clarity.
]
"src/StreamDeck/Transport/*.py" = [
	'S110', # We swallow exceptions in the transport layer.
	'E722', # We swallow *all* exceptions in places in the transport layer.
]
